models.py
from app import db
from datetime import datetime
import re


def slugify(title):
    pattern = r'[^\w+]'
    title = re.sub(' ', '', title)
    slug = re.sub(pattern, '-', title)
    return "{}".format(slug)


post_tags = db.Table('post_tags',
                     db.Column('post_id', db.Integer, db.ForeignKey('tag.id')),
                     db.Column('tag_id', db.Integer, db.ForeignKey('post.id'))
                     )


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(140))
    slug = db.Column(db.String(140), unique=True)
    body = db.Column(db.Text)
    created = db.Column(db.DateTime, default=datetime.now())

    tags = db.relation('Tag', secondary=post_tags, backref=db.backref('posts', lazy='dynamic'))

    def __init__(self, *args, **kwargs):
        super(Post, self).__init__(*args, **kwargs)
        self.generate_slug()

    def generate_slug(self):
        if self.title:
            self.slug = slugify(self.title)

    def __repr__(self):
        return '<Post id: {}, title: {}>'.format(self.id, self.title)


class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), unique=True)
    slug = db.Column(db.String(100), unique=True)

    def __init__(self, *args, **kwargs):
        super(Tag, self).__init__(*args, **kwargs)
        self.slug = slugify(self.name)

    def __repr__(self):
        return '<Tag id: {}, name: {}>'.format(self.id, self.name)

posts/forms.py
from wtforms import Form, StringField, TextAreaField


class PostForm(Form):
    title = StringField('Title')
    body = TextAreaField('Body')

app.py
from flask import Flask
from config import Configuration

from flask_sqlalchemy import SQLAlchemy

from flask_migrate import Migrate, MigrateCommand
from flask_script import Manager


app = Flask(__name__)
app.config.from_object(Configuration)

db = SQLAlchemy(app)

migrate = Migrate(app, db)
manager = Manager(app)

manager.add_command('db', MigrateCommand)

main.py
from app import app
from app import db

from posts.blueprint import posts

import view

app.register_blueprint(posts, url_prefix='/blog')

if __name__ == '__main__':
    app.run()

posts/blueprint.py
from flask import Blueprint
from flask import render_template

from models import Post, Tag
from app import db

from flask import request

from .forms import PostForm

from flask import redirect, url_for

posts = Blueprint('posts', __name__, template_folder='templates')


@posts.route('/create', methods=["POST", "GET"])
def create_post():
    if request.method == "POST":
        title = request.form['title']
        body = request.form['body']
        tags = request.form.getlist('tags')
        try:
            post = Post(title=title, body=body)
            for tag in tags:
                obj_tag = Tag.query.filter(Tag.name == tag).first()
                post.tags.append(obj_tag)
            db.session.add(post)
            db.session.commit()
        except:
            print('Error')
        return redirect(url_for('posts.index'))
    else:
        tags = Tag.query.all()
        form = PostForm()
        return render_template('posts/create_post.html', form=form, tags=tags)


@posts.route('/')
def index():
    query = request.args.get('query')
    page = request.args.get('page')

    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    if query:
        posts = Post.query.filter(Post.title.contains(query) | Post.body.contains(query))
    else:
        posts = Post.query

    pages = posts.paginate(page=page, per_page=3)

    return render_template('posts/index.html', pages=pages)


@posts.route('/<slug>')
def post_detail(slug):
    post = Post.query.filter(Post.slug == slug).first()
    return render_template('posts/post_detail.html', post=post)


@posts.route('/tag/<slug>')
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug == slug).first()
    return render_template('posts/tag_detail.html', tag=tag)

posts/templates/posts/create_post.html
{% extends 'base.html' %}

{% block title %}
	Create new post
{% endblock %}

{% block content_title %}
	New Post
{% endblock %}

{% block content %}
	<div class="container">
		<form action="{{ url_for('posts.create_post') }}" method="POST">
			{% for field in form %}
					<div class="form-group">
						{{ field.label() }}
						{{ field(class="form-control") }}
					</div>
			{% endfor %}
			<div class="form-group">
				<label class="d-block">Tags</label>
				{% for tag in tags %}
					<label class="badge badge-secondary" for="{{ tag.id }}" id="label-{{ tag.id }}">{{ tag.name }}</label>
					<input type="checkbox" class="d-none" id="{{ tag.id }}" onchange="toggleCheckbox(this)" value="{{ tag.name }}" name='tags'>
				{% endfor %}
			</div> 
			<button type="submit" class="btn btn-primary">Create</button>
		</form>
	</div>
	<script>
		function toggleCheckbox(checkbox) {
			label = document.getElementById('label-'+checkbox.id);
			if (checkbox.checked){
				label.classList.remove("badge-secondary");
				label.classList.add("badge-success");
			}	
			else{
				label.classList.remove("badge-success");
				label.classList.add("badge-secondary");
			}
		}
	</script>
{% endblock %}

posts/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
	All Posts
{% endblock %}

{% block content_title %}
	All Posts
{% endblock %}

{% block content %}
	<div class="container">
	{% for post in pages.items %}
		<p>		
			<a href="{{ url_for('posts.post_detail',slug=post.slug) }}">{{ post.title }}</a>
		</p>
	{% endfor %}
		<div class="row">
			<nav aria-label="Page navigation example">
			  <ul class="pagination">
			    <li class="page-item {% if not pages.has_prev %} disabled {% endif %}"><a class="page-link" href="./?page={{ pages.prev_num }}">Previous</a></li>
			    {% for page in pages.iter_pages() %}
			    	<li class="page-item {% if page == pages.page %} active {% endif %}"><a class="page-link" href="./?page={{ page }}">{{ page }}</a></li>
			    {% endfor %}
			    <li class="page-item {% if not pages.has_next %} disabled {% endif %}"><a class="page-link" href="./?page={{ pages.next_num }}">Next</a></li>
			  </ul>
			</nav>
		</div>
	</div>
{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %}
	Post Page
{% endblock %}

{% block content_title %}
	<h3>{{ post.title }}</h3>
{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-md-12">			
			<p>{{ post.body }}</p>
		</div>
	</div>
	<div class="row">
		<div class="col-md-6">
			{% for tag in post.tags %}
				<a href="{{ url_for('posts.tag_detail', slug=tag.slug) }}">
					<span class="badge badge-secondary">{{ tag.name }}</span>
				</a>
			{% endfor %}
		</div>
	</div>
</div>
{% endblock %}

posts/templates/posts/tag_detail.html
{% extends 'base.html' %}

{% block title %}
	{{ tag.name }}
{% endblock %}

{% block content_title %}
	Posts for tag: {{ tag.name }}
{% endblock %}

{% block content %}
<div class="container">
	{% for post in tag.posts %}
	<div class="row">
		<div class="col-md-12">		
			<a href="{{ url_for('posts.post_detail',slug=post.slug) }}">{{ post.title }}</a>
		</div>
	</div>
	{% endfor %}
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>
		{% block title %}
		{% endblock %} | Flask
	</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	  <a class="navbar-brand" href="{{ url_for('index') }}">Flask</a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav mr-auto">
	      <li class="nav-item">
	        <a class="nav-link {% if request.url_rule.endpoint == 'index' %}active{% endif %}" href="{{ url_for('index') }}">Home <span class="sr-only">(current)</span></a>
	      </li>
	      <li class="nav-item">
	        <a class="nav-link {% if request.url_rule.endpoint == 'posts.index' %}active{% endif %}" href="{{ url_for('posts.index') }}">Blog</a>
	      </li>
	      <li class="nav-item">
	      	<a href="{{ url_for('posts.create_post') }}" class="btn btn-outline-success">Create Post</a>
	      </li>
	    </ul>
	    <form class="form-inline my-2 my-lg-0" method="GET" action="{{ url_for('posts.index') }}">
	      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="query" value="{{ request.args.get('query', '') }}">
	      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
	    </form>
	  </div>
	</nav>	
	<div class="container">
		<div class="row">
			<h1>
				{% block content_title%}
				{% endblock %}
			</h1>
		</div>
	</div>
	{% block content%}
	{% endblock %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}
	Index Page
{% endblock %}

{% block content_title %}
	Hello, {{ name }}
{% endblock %}

{% block content %}
	<div class="container">
		<a href="{{ url_for('posts.create_post') }}" class="btn btn-success">Create Post</a>
	</div>
{% endblock %}